services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://akash:password@db:5432/postgresDB?schema=public
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgresDB
      - POSTGRES_USER=akash
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: