
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: my_express_app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:mypassword@localhost:5432/postgres?sslmode=disable
    ports:
      - "3000:3000"

volumes:
  postgres_data: